### ISSUE TITLE
Not working for Brother HL-L3230CDW

### ISSUE THREAD

**Issue by rjoomen** [mhaid/de.mhaid.brother#1]
Nice that you've developed a Brother printer app, thanks. Unfortunately it does not work for my Brother HL-L3230CDW color laser printer. It shows the printer to be 'not unavailable', but no toner levels are shown. I've tried reinstalling app and device, but that didn't help.

Do you have any suggestions as to how I can help debug and solve this issue?

**Comment by mhaid** [comment]
Hey rjoomen,

unfortunatly I'm not familiar with the HL-Series.

Could you please check, weather the "web based management" of your printer **requires an authentication?**
You can do that by simply entering the IP-Address of your printer into the address bar of a web browser of your choice.
If you can see the status page with the toner-level straight away, there should be no authentication required.

In any case, **please also do the following**:
1. Remove the printer from homey
2. Install the new beta-version of the brother-app: https://homey.app/de-de/app/de.mhaid.brother/Brother-Drucker/test/
3. Re-add the printer to homey
4. After a couple of minutes send me an diagnosis report:
(1) Open the "More" tab in the homey app
(2) Click on "Apps"
(3) Click on "Brother-Printer"
(4) Klick on the setting-symbol in the top right corner
(5) Press "Send diagnosis report" and enter any message you'd like

Best regards,
Morris

**Comment by rjoomen** [comment]
Hi Morris, thanks for the test version. I installed it and this time my printer was recognized (no authentication, btw). Unfortunately, at some point afterwards, the data stopped being updated. I also tested switching off the printer, but the device in Homey did not notice this, neither did it notice when the printer was switched on again. I created a report with code 68f1e0f2-d110-42fa-8acb-f752917ad6be.

Another question: would it be possible to make a field with the current device status of the printer ("Please Wait"/"Ready"/"Sleep"/"Printing", etc)? That field could also be used for availability by setting it to "Unavailable" when the printer is not reachable.

FYI: Home Assistant has a good Brother integration, source code [here](https://github.com/home-assistant/core/tree/dev/homeassistant/components/brother).

**Comment by mhaid** [comment]
Hello Rjoomen,

I have completely rewritten the application so that it can support a wider range of devices.
Hopefully your printer will work with the new version as well:
https://homey.app/de-de/app/de.mhaid.brother/Brother-Drucker/test/

Let me know how well your printer works with the new version :)

BR, Morris

**Comment by rjoomen** [comment]
I've tried v1.1.0, and it indeed shows a lot more data. This is great, thanks. It does not detect when I switch off the printer, though, the status stayed at sleep and Unavailable at No. When switching on again, the status was correctly updated to Ready, so reconnecting works. 

Regards, Roelof

P.S. New report: e41e4032-8d2f-4b3b-87ee-86e7f48fafed

**Comment by mhaid** [comment]
Hello Roelof,

thank you for your feedback. I have changed the unavailability check. Before, the printer had to be unavailable 5 times (5x 15min). Now the printer is set to unavailable after the first timeout.

If you want, you can of course try it out:
https://homey.app/de-de/app/de.mhaid.brother/Brother-Drucker/test/

Best regards,
Morris
