### ISSUE TITLE
Brother MFC-J4540DW

### ISSUE THREAD

**Issue by GitMike1233** [mhaid/de.mhaid.brother#2]
Hello,
Thanks for the app for the Brother printers.
I did use it for a MFC-J4510DW and that worked great.
But now I use a MFC-J4540DW and I don't get any info.
But i have read the other post and I saw something about authentication.
Is that ment the password what is written on the back of the printer?
If i remove the password it would proberly work?
If so, I will try to find how I can remove it.

I can see the ink level without logging in. But not in the app. 
a391983d-f6d1-41fa-b151-f6fc95d364c6

Best regards.

After 2 hours of my first edit my device is recognised and all the values are in the app.

Tanks.

**Comment by mhaid** [comment]
Hello Mike,
Thank you for the diagnostic report.
The SNMP request is timing out, so the app cannot retrieve data from your printer.

Please check if snmpv1+v2+v3 protocol is enabled in printer settings:
https://support.brother.com/g/s/id/htmldoc/mfc/cv_mfc4340dw/uke/html/GUID-1CF747A9-BECD-4001-9921-0ACA3BA67062_1.html?c=de&lang=de&prod=mfcj4540dw_eu_as&KEY=snmp

BR, Morris

**Comment by GitMike1233** [comment]
Thanks for your answer.
The time was synced But the ink level not.
I have looked at the snmp.
The read/write of v1+2 was enabled.
V3 not.
For now i have enabled r/w V3 en read only v1+2..

Edit. I now think the ink level only changes the last sync time when it was changed, am I correct? 
The time of the device and the device status are changing correct. Time last 5 minutes, status, last 9 hours. 
Ink level, last 2 days. 

![20230807_073139](https://github.com/mhaid/de.mhaid.brother/assets/46908044/249c8501-0bf4-4a7b-8663-cafb31469e74)

**Comment by mhaid** [comment]
Hello Mike,
yes, you are correct:

- **last sync time**: Time when Homey last requested information from the printer.

- **Ink level change** (XX hours/days ago): Changes only if the ink level value has changed. Of course, the same is true for device status and all other properties.

So do I understand it correctly that the ink level is now displayed correctly?

BR, Morris

**Comment by GitMike1233** [comment]
Hello Morris,

You understood correct, the inklevel and the others are displayed correctly.
Don't know the exact polling time but the time was synced 12 minutes ago. So that looks also good. 
So everything works fine.

Best regards, Mike.
